def city(ln, street):
    if ln.find("Город") != -1:
        ln = ln.replace(" Город ", f" {street} ")
        ln = "г. " + ln
    elif ln.find("Поселок городского типа") != -1:
        ln = ln.replace(" Поселок городского типа ", f" {street} ")
        ln = "пгт. " + ln
    elif ln.find("Рабочий поселок") != -1:
        ln = ln.replace(" Рабочий поселок ", f" {street} ")
        ln = "рп. " + ln
    elif ln.find("Поселок") != -1:
        ln = ln.replace(" Поселок ", f" {street} ")
        ln = "п. " + ln
    elif ln.find("Село") != -1:
        ln = ln.replace(" Село ", f" {street} ")
        ln = "с. " + ln
    return ln


file_out = open("adreses.txt", "w", encoding="utf-8")
with open("adreses.txt", "r", encoding="utf-8") as f:
    for line in f:
        flag = False
        if line.find("Промзона") != -1 or line.find("Абонентский ящик") != -1 or line.find("Мост") != -1 or \
                line.find("Казарма") != -1 or line.find("Участок") != -1 or line.find("Месторождение") != -1 or \
                line.find("Железнодорожный пост") != -1 or line.find("Почтовое отделение") != -1 or \
                line.find("Местность") != -1 or line.find("Фермерское хозяйство") != -1 or \
                line.find("Некоммерческое партнерство") != -1:
            continue
        elif line.find("Улица") != -1:
            line = line.replace(f" Улица", "")
            line = city(line, "ул.")
            flag = True
        elif line.find("Переулок") != -1:
            line = line.replace(f" Переулок", "")
            line = city(line, "пер.")
            flag = True
        elif line.find("Проезд") != -1:
            line = line.replace(f" Проезд", "")
            line = city(line, "пр-д")
            flag = True
        elif line.find("Площадь") != -1:
            line = line.replace(f" Площадь", "")
            line = city(line, "пл.")
            flag = True
        elif line.find("Шоссе") != -1:
            line = line.replace(f" Шоссе", "")
            line = city(line, "ш.")
            flag = True
        elif line.find("Ряд(ы)") != -1:
            line = line.replace(f" Ряд(ы)", "")
            line = city(line, "ряд")
            flag = True
        elif line.find("Ряды") != -1:
            line = line.replace(f" Ряды", "")
            line = city(line, "ряд")
            flag = True
        elif line.find("Проспект") != -1:
            line = line.replace(f" Проспект", "")
            line = city(line, "пр-кт")
            flag = True
        elif line.find("Площадка") != -1:
            line = line.replace(f" Площадка", "")
            line = city(line, "пл-ка")
            flag = True
        elif line.find("Тракт") != -1:
            line = line.replace(f" Тракт", "")
            line = city(line, "тракт")
            flag = True
        elif line.find("Километр") != -1:
            line = line.replace(f" Километр", "")
            line = city(line, "км")
            flag = True
        elif line.find("Бульвар") != -1:
            line = line.replace(f" Бульвар", "")
            line = city(line, "б-р")
            flag = True
        elif line.find("Тупик") != -1:
            line = line.replace(f" Тупик", "")
            line = city(line, "туп.")
            flag = True
        elif line.find("Набережная") != -1:
            line = line.replace(f" Набережная", "")
            line = city(line, "наб.")
            flag = True
        elif line.find("Дорога") != -1:
            line = line.replace(f" Дорога", "")
            line = city(line, "дор.")
            flag = True
        elif line.find("Спуск") != -1:
            line = line.replace(f" Спуск", "")
            line = city(line, "с-к")
            flag = True
        elif line.find("Линия") != -1:
            line = line.replace(f" Линия", "")
            line = city(line, "лн.")
            flag = True
        elif line.find("Квартал") != -1:
            line = line.replace(f" Квартал", "")
            line = city(line, "кв-л")
            flag = True
        elif line.find("Садовое неком-е товарищество") != -1:
            line = line.replace(f" Садовое неком-е товарищество", "")
            line = city(line, "тер. СНТ")
            flag = True
        elif line.find("Гаражно-строительный кооп.") != -1:
            line = line.replace(f" Гаражно-строительный кооп.", "")
            line = city(line, "тер. ГСК")
            flag = True
        elif line.find("Дачное неком-е партнерство") != -1:
            line = line.replace(f" Дачное неком-е партнерство", "")
            line = city(line, "тер. ДНП")
            flag = True
        elif line.find("Микрорайон") != -1:
            line = line.replace(f" Микрорайон", "")
            line = city(line, "мкр.")
            flag = True
        elif line.find("Станция") != -1:
            line = line.replace(f" Станция", "")
            line = city(line, "ст.")
            flag = True
        elif line.find("Сад") != -1:
            line = line.replace(f" Сад", "")
            line = city(line, "сад")
            flag = True
        elif line.find("Деревня") != -1:
            line = line.replace(f" Деревня", "")
            line = city(line, "д.")
            flag = True
        elif line.find("Жилой район") != -1:
            line = line.replace(f" Жилой район", "")
            line = city(line, "ж/р")
            flag = True
        elif line.find("Район") != -1:
            line = line.replace(f" Район", "")
            line = city(line, "р-н")
            flag = True
        elif line.find("Остров") != -1:
            line = line.replace(f" Остров", "")
            line = city(line, "ост-в")
            flag = True
        elif line.find("Проулок") != -1:
            line = line.replace(f" Проулок", "")
            line = city(line, "проул.")
            flag = True
        elif line.find("Зона") != -1:
            line = line.replace(f" Зона", "")
            line = city(line, "зона")
            flag = True
        elif line.find("Кольцо") != -1:
            line = line.replace(f" Кольцо", "")
            line = city(line, "к-цо")
            flag = True
        elif line.find("Парк") != -1:
            line = line.replace(f" Парк", "")
            line = city(line, "парк")
            flag = True
        elif line.find("Городок") != -1:
            line = line.replace(f" Городок", "")
            line = city(line, "г-к")
            flag = True
        elif line.find("Хутор") != -1:
            line = line.replace(f" Хутор", "")
            line = city(line, "х.")
            flag = True
        elif line.find("Переезд") != -1:
            line = line.replace(f" Переезд", "")
            line = city(line, "пер-д")
            flag = True
        elif line.find("Платформа") != -1:
            line = line.replace(f" Платформа", "")
            line = city(line, "платф.")
            flag = True
        elif line.find("Разъезд") != -1:
            line = line.replace(f" Разъезд", "")
            line = city(line, "рзд.")
            flag = True
        elif line.find("Аллея") != -1:
            line = line.replace(f" Аллея", "")
            line = city(line, "ал.")
            flag = True
        elif line.find("Сквер") != -1:
            line = line.replace(f" Сквер", "")
            line = city(line, "с-р")
            flag = True
        elif line.find("Рабочий Поселок") != -1:
            line = line.replace(f" Рабочий Поселок", "")
            line = city(line, "рп.")
            flag = True
        elif line.find("Въезд") != -1:
            line = line.replace(f" Въезд", "")
            line = city(line, "взд.")
            flag = True
        elif line.find("Заезд") != -1:
            line = line.replace(f" Заезд", "")
            line = city(line, "ззд.")
            flag = True
        elif line.find("Поселок") != -1:
            line = line.replace(f" Поселок", "")
            line = city(line, "ззд.")
            flag = True
        elif line.find("Вал") != -1:
            line = line.replace(f" Вал", "")
            line = city(line, "вал")
            flag = True
        elif line.find("Коса") != -1:
            line = line.replace(f" Коса", "")
            line = city(line, "коса")
            flag = True
        elif line.find("Просек") != -1:
            line = line.replace(f" Просек", "")
            line = city(line, "пр-к")
            flag = True
        elif line.find("Просека") != -1:
            line = line.replace(f" Просека", "")
            line = city(line, "пр-ка")
            flag = True
        elif line.find("Проселок") != -1:
            line = line.replace(f" Проселок", "")
            line = city(line, "пр-лок")
            flag = True
        elif line.find("Населенный пункт") != -1:
            line = line.replace(f" Населенный пункт", "")
            line = city(line, "нп.")
            flag = True
        elif line.find("Село") != -1:
            line = line.replace(f" Село", "")
            line = city(line, "с.")
            flag = True
        elif line.find("Строение") != -1:
            line = line.replace(f" Строение", "")
            line = city(line, "стр.")
            flag = True
        elif line.find("Магистраль") != -1:
            line = line.replace(f" Магистраль", "")
            line = city(line, "мгстр.")
            flag = True
        elif line.find("Слобода") != -1:
            line = line.replace(f" Слобода", "")
            line = city(line, "сл.")
            flag = True
        elif line.find("Местечко") != -1:
            line = line.replace(f" Местечко", "")
            line = city(line, "м-ко")
            flag = True
        elif line.find("Взвоз") != -1:
            line = line.replace(f" Взвоз", "")
            line = city(line, "взв.")
            flag = True
        elif line.find("Усадьба") != -1:
            line = line.replace(f" Усадьба", "")
            line = city(line, "ус.")
            flag = True
        elif line.find("Берег") != -1:
            line = line.replace(f" Берег", "")
            line = city(line, "б-г")
            flag = True
        elif line.find("Железнодорожная платформа") != -1:
            line = line.replace(f" Железнодорожная платформа", "")
            line = city(line, "ж/д пл-ма")
            flag = True
        elif line.find("Железнодорожная станция") != -1:
            line = line.replace(f" Железнодорожная станция", "")
            line = city(line, "ж/д ст.")
            flag = True
        elif line.find("ж/д останов. (обгонный) пункт") != -1:
            line = line.replace(f" ж/д останов. (обгонный) пункт", "")
            line = city(line, "ж/д о.п.")
            flag = True
        elif line.find("Железнодорожная будка") != -1:
            line = line.replace(f" Железнодорожная будка", "")
            line = city(line, "ж/д б-ка")
            flag = True
        elif line.find("Железнодорожный разъезд") != -1:
            line = line.replace(f" Железнодорожный разъезд", "")
            line = city(line, "ж/д рзд.")
            flag = True
        elif line.find("Железнодорожная казарма") != -1:
            line = line.replace(f" Железнодорожная казарма", "")
            line = city(line, "ж/д к-ма")
            flag = True
        elif line.find("Территория СНТ") != -1:
            line = line.replace(f" Территория СНТ", "")
            line = city(line, "тер. СНТ")
            flag = True
        elif line.find("Территория ОНТ") != -1:
            line = line.replace(f" Территория ОНТ", "")
            line = city(line, "тер. ОНТ")
            flag = True
        elif line.find("Территория ТСН") != -1:
            line = line.replace(f" Территория ТСН", "")
            line = city(line, "тер. ТСН")
            flag = True
        elif line.find("Территория ДНТ") != -1:
            line = line.replace(f" Территория ДНТ", "")
            line = city(line, "тер. ДНТ")
            flag = True
        elif line.find("Территория СПК") != -1:
            line = line.replace(f" Территория СПК", "")
            line = city(line, "тер. СПК")
            flag = True
        elif line.find("Территория ДПК") != -1:
            line = line.replace(f" Территория ДПК", "")
            line = city(line, "тер. ДПК")
            flag = True
        elif line.find("Территория ГСК") != -1:
            line = line.replace(f" Территория ГСК", "")
            line = city(line, "тер. ГСК")
            flag = True
        elif line.find("Территория СНП") != -1:
            line = line.replace(f" Территория СНП", "")
            line = city(line, "тер. СНП")
            flag = True
        elif line.find("Территория ФХ") != -1:
            line = line.replace(f" Территория ФХ", "")
            line = city(line, "тер.ф.х.")
            flag = True
        elif line.find("Территория ФХ") != -1:
            line = line.replace(f" Территория ФХ", "")
            line = city(line, "тер.ф.х.")
            flag = True
        elif line.find("Территория ДНП") != -1:
            line = line.replace(f" Территория ДНП", "")
            line = city(line, "тер. ДНП")
            flag = True
        elif line.find("Территория СОСН") != -1:
            line = line.replace(f" Территория СОСН", "")
            line = city(line, "тер. СОСН")
            flag = True
        elif line.find("Территория ОНО") != -1:
            line = line.replace(f" Территория ОНО", "")
            line = city(line, "тер. ОНО")
            flag = True
        elif line.find("Территория ПК") != -1:
            line = line.replace(f" Территория ПК", "")
            line = city(line, "тер. ПК")
            flag = True
        elif line.find("Территория СНО") != -1:
            line = line.replace(f" Территория СНО", "")
            line = city(line, "тер. СНО")
            flag = True
        elif line.find("Территория ДНО") != -1:
            line = line.replace(f" Территория ДНО", "")
            line = city(line, "тер. ДНО")
            flag = True
        elif line.find("Территория") != -1:
            line = line.replace(f" Территория", "")
            line = city(line, "тер.")
            flag = True
        if flag:
            file_out.write(line)
        else:
            print(line)
file_out.close()
